// SPDX-License-Identifier: AGPL-3.0-only
#include <bim/app/random_bot_name.hpp>

#include <iscool/random/rand.hpp>

static const std::string_view g_bot_names[] = { "A.X.L. 🔩",
                                                "AMEE 🔩",
                                                "AUTO 🔩",
                                                "Adam 🔩",
                                                "Adam Link 🔩",
                                                "Alfie 🔩",
                                                "Alpha 5 🔩",
                                                "Alpha 6 🔩",
                                                "Alpha 7 🔩",
                                                "Alsatia Zevo 🔩",
                                                "Andrew 🔩",
                                                "Andromon 🔩",
                                                "Aniel 🔩",
                                                "Arale 🔩",
                                                "Astor 🔩",
                                                "Astro Boy 🔩",
                                                "Atmophytes 🔩",
                                                "Automaton 🔩",
                                                "B-4 🔩",
                                                "B.A.T.s 🔩",
                                                "B.E.N. 🔩",
                                                "B166ER 🔩",
                                                "BB-8 🔩",
                                                "Baymax 🔩",
                                                "Bender 🔩",
                                                "Beta-Machine 🔩",
                                                "Billybot 🔩",
                                                "Bishop 🔩",
                                                "Bocoe 🔩",
                                                "Boilerplate 🔩",
                                                "Bokkun 🔩",
                                                "Boppers 🔩",
                                                "Bors 🔩",
                                                "Brackenridge 🔩",
                                                "Brainbots 🔩",
                                                "Buffybot 🔩",
                                                "Byron 🔩",
                                                "C-16 🔩",
                                                "C-17 🔩",
                                                "C-18 🔩",
                                                "C-19 🔩",
                                                "C.A.R.R. 🔩",
                                                "CASE 🔩",
                                                "CHAPPiE 🔩",
                                                "CHIP 🔩",
                                                "Calculators 🔩",
                                                "Cambot 🔩",
                                                "Candy Droober 🔩",
                                                "Canti 🔩",
                                                "Cast-Iron Man 🔩",
                                                "Cherry 2000 🔩",
                                                "Chitti 🔩",
                                                "Chucky 🔩",
                                                "Chumblies 🔩",
                                                "Clunk 🔩",
                                                "Coconuts 🔩",
                                                "Coldfire 🔩",
                                                "Coldstone 🔩",
                                                "Conky 2000 🔩",
                                                "Coyote 🔩",
                                                "Crow T. Robot 🔩",
                                                "Cutie 🔩",
                                                "Cylons 🔩",
                                                "D.A.R.Y.L. 🔩",
                                                "D.A.V.E. 🔩",
                                                "DOR-15 🔩",
                                                "DRN-0167 🔩",
                                                "DV-8 🔩",
                                                "Damon 🔩",
                                                "Darkhawks 🔩",
                                                "David 8 🔩",
                                                "Dee Model 🔩",
                                                "Demerzel 🔩",
                                                "Docoe 🔩",
                                                "Dorfl 🔩",
                                                "Dot Matrix 🔩",
                                                "Doyle 🔩",
                                                "ED-209 🔩",
                                                "EDI 🔩",
                                                "EVE 🔩",
                                                "Eighter 🔩",
                                                "Elio 🔩",
                                                "Emma-2 🔩",
                                                "Engimals 🔩",
                                                "Ez-27 🔩",
                                                "Freya 🔩",
                                                "Freysa 🔩",
                                                "G.U.A.R.D.O. 🔩",
                                                "G2 🔩",
                                                "GERTY 3000 🔩",
                                                "GIR 🔩",
                                                "Gabriel 🔩",
                                                "Giant Robo 🔩",
                                                "Giddy 🔩",
                                                "Gigantor 🔩",
                                                "Glowboo 🔩",
                                                "Gnut 🔩",
                                                "Goddard 🔩",
                                                "Golden Army 🔩",
                                                "Gort 🔩",
                                                "Grounder 🔩",
                                                "Guardromon 🔩",
                                                "Gypsy 🔩",
                                                "H.E.L.P.eR. 🔩",
                                                "Hadaly 🔩",
                                                "Hangman 🔩",
                                                "Haro 🔩",
                                                "Helen O'Loy 🔩",
                                                "Helena 🔩",
                                                "Huggy 🔩",
                                                "Humanoids 🔩",
                                                "Iron Giant 🔩",
                                                "Iron Man 🔩",
                                                "J20 🔩",
                                                "Jay-Dub 🔩",
                                                "Jenkins 🔩",
                                                "Jenny Wakeman 🔩",
                                                "Jinx 🔩",
                                                "Johnny 5 🔩",
                                                "Johnny Cab 🔩",
                                                "K-2SO 🔩",
                                                "K9 🔩",
                                                "KARR 🔩",
                                                "KITT 🔩",
                                                "Karaibots 🔩",
                                                "Kay-Em 14 🔩",
                                                "Kikaider 🔩",
                                                "Killbots 🔩",
                                                "Kirby 🔩",
                                                "Klapaucius 🔩",
                                                "Krybots 🔩",
                                                "Kryten 🔩",
                                                "L-76 🔩",
                                                "L3-37 🔩",
                                                "Lenny 🔩",
                                                "Leon Kowalski 🔩",
                                                "M3Gan 🔩",
                                                "MARK13 🔩",
                                                "MD 63 🔩",
                                                "MM7 🔩",
                                                "Mac 🔩",
                                                "Manders 🔩",
                                                "Mandroid 🔩",
                                                "Mariette 🔩",
                                                "Marius 🔩",
                                                "Marvin 🔩",
                                                "Mary 25 🔩",
                                                "MecWilly 🔩",
                                                "Mech Eagles 🔩",
                                                "Mechagodzilla 🔩",
                                                "Mechonoids 🔩",
                                                "Megazords 🔩",
                                                "Melfina 🔩",
                                                "Metal giants 🔩",
                                                "Metal men 🔩",
                                                "Miyu Greer 🔩",
                                                "Moravecs 🔩",
                                                "Mordel 🔩",
                                                "Morgan 🔩",
                                                "Mr. Split 🔩",
                                                "Mr. Static 🔩",
                                                "Neotnia 🔩",
                                                "Newman 🔩",
                                                "Nimani 🔩",
                                                "Nimrod 🔩",
                                                "Nimue Alban 🔩",
                                                "Norby 🔩",
                                                "OX King 🔩",
                                                "Okra 🔩",
                                                "Olimpia 🔩",
                                                "Olympia 🔩",
                                                "Omnidroid 🔩",
                                                "P.O.P.S 🔩",
                                                "Pax Magelanic 🔩",
                                                "Phatasaur 🔩",
                                                "Pino Petto 🔩",
                                                "Pixal 🔩",
                                                "Primus 🔩",
                                                "Pris 🔩",
                                                "Project 2501 🔩",
                                                "Quinn 🔩",
                                                "R.A.L.F 🔩",
                                                "R.I.C. 2.0 🔩",
                                                "R.O.T.O.R. 🔩",
                                                "R4-P17 🔩",
                                                "RIA 🔩",
                                                "Rabbot 🔩",
                                                "Rachael 🔩",
                                                "Radius 🔩",
                                                "Recognizers 🔩",
                                                "Replicators 🔩",
                                                "Rex 🔩",
                                                "Rick Deckard 🔩",
                                                "Rob-Monkey 🔩",
                                                "Robbie 🔩",
                                                "Robi 🔩",
                                                "Robo 🔩",
                                                "RoboGadget 🔩",
                                                "Robositter 🔩",
                                                "Robot 7 🔩",
                                                "Robot Jones 🔩",
                                                "Robotboy 🔩",
                                                "Roboto 🔩",
                                                "Roderick 🔩",
                                                "Rommie 🔩",
                                                "Roy Batty 🔩",
                                                "S.A.R.-003 🔩",
                                                "S.O.P.H.I.E 🔩",
                                                "S1MONE 🔩",
                                                "SHROUD 🔩",
                                                "SI-9 🔩",
                                                "SID 6.7 🔩",
                                                "SIMON 🔩",
                                                "Sapper Morton 🔩",
                                                "Scratch 🔩",
                                                "Setaur 🔩",
                                                "Sheila 🔩",
                                                "Sico 🔩",
                                                "Slim John 🔩",
                                                "Solo 🔩",
                                                "Sonny+ NS4 🔩",
                                                "Sox 🔩",
                                                "Speedy 🔩",
                                                "Spofforth 🔩",
                                                "Spot 🔩",
                                                "Steel 🔩",
                                                "Stitchpunks 🔩",
                                                "Sulla 🔩",
                                                "Syder robots 🔩",
                                                "T-1000 🔩",
                                                "T-800 🔩",
                                                "T-850 🔩",
                                                "T-Bob 🔩",
                                                "T-X 🔩",
                                                "TARS 🔩",
                                                "Tachikoma 🔩",
                                                "Terminator 🔩",
                                                "Terminatrix 🔩",
                                                "Terminus 🔩",
                                                "Tet 🔩",
                                                "Toaster 🔩",
                                                "Tom Servo 🔩",
                                                "Tony 🔩",
                                                "Trace Mayter 🔩",
                                                "Trurl 🔩",
                                                "US 47 🔩",
                                                "Ultron 🔩",
                                                "Ulyssses 🔩",
                                                "UniBlab 🔩",
                                                "Valerie 23 🔩",
                                                "Vision 🔩",
                                                "Voltron 🔩",
                                                "WALL-E 🔩",
                                                "Walter One 🔩",
                                                "Weebo 🔩",
                                                "XJ-9 🔩",
                                                "Yod 🔩",
                                                "Z-1 🔩",
                                                "Z-2 🔩",
                                                "Z-3 🔩",
                                                "Zane 🔩",
                                                "Zane Gort 🔩",
                                                "Zat 🔩",
                                                "Zeta 🔩",
                                                "Zhora 🔩",
                                                "Zoromes 🔩" };

std::string_view bim::app::random_bot_name()
{
  return *iscool::random::rand::get_default().random_in_sequence(
      std::begin(g_bot_names), std::end(g_bot_names));
}
