version: "3.8"
services:
  gs:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - ${PORT}:${PORT}/udp
    volumes:
      - ./bin:/opt/bim/bin:ro
      - ./etc:/opt/bim/etc:ro
      - ./log:/opt/bim/log
      - ./contest:/opt/bim/contest/
    deploy:
      restart_policy:
        condition: on-failure
    command: /opt/bim/bin/bim-server-launcher.sh "${PORT}"
