// SPDX-License-Identifier: AGPL-3.0-only
#include <bim/server/config.hpp>

bim::server::config::config()
  : port(65535)
  , random_seed(0)
  , session_clean_up_interval(std::chrono::minutes(3))
  , session_removal_delay(std::chrono::minutes(3))
  , matchmaking_clean_up_interval(std::chrono::minutes(3))
  , random_game_auto_start_delay(std::chrono::seconds(20))
  , game_service_clean_up_interval(std::chrono::minutes(3))
  , game_service_disconnection_lateness_threshold_in_ticks(75)
  , game_service_disconnection_earliness_threshold_in_ticks(75)
  , game_service_disconnection_inactivity_delay(std::chrono::seconds(10))
  , game_service_max_duration_for_short_game(std::chrono::seconds(0))
  , game_service_coins_per_victory(0)
  , game_service_coins_per_defeat(0)
  , game_service_coins_per_draw(0)
  , game_service_coins_per_short_game_victory(0)
  , game_service_coins_per_short_game_defeat(0)
  , game_service_coins_per_short_game_draw(0)
  , enable_contest_timeline_recording(false)
  , geolocation_clean_up_interval(std::chrono::days(7))
  , geolocation_update_interval(std::chrono::days(7))
  , enable_geolocation(false)
  , enable_statistics_log(false)
  , enable_rolling_statistics(false)
  , statistics_dump_delay(std::chrono::seconds(60))
  , enable_discord_matchmaking_notifications(false)
  , discord_matchmaking_notification_interval(std::chrono::seconds(60))
  , enable_karma(false)
  , karma_blacklisting_duration(std::chrono::minutes(30))
  , initial_karma_value(100)
  , disconnection_karma_adjustment(-10)
  , short_game_karma_adjustment(-30)
  , good_behavior_karma_adjustment(2)
{}
