---
name: Repository health

on:
  push:
  pull_request:

concurrency:
  group: >
    ${{github.workflow }}
    -${{ github.event.pull_request.number || github.ref}}

  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    container: "ubuntu:25.04"

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install dependencies
        run: >
          apt-get update ;
          apt-get install --yes black clang-format shellcheck yamllint ;

      - name: Check repository state
        run: ./ci/repository-health.sh
